---
- name: Update repositories
  hosts: all
  become: yes

  tasks:
    - name: Update package cache (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update package cache (CentOS)
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Upgrade packages (CentOS)
      yum:
        name: "*"
        state: "latest"
      when: ansible_distribution == "CentOS"

    - name: Upgrade packages (Ubuntu)
      apt:
        upgrade: yes
      when: ansible_distribution == "Ubuntu"
